//go:build !wasm
// DO NOT EDIT. generated by github.com/tinywasm/orm

package clinicalencounter

import (
	"github.com/tinywasm/orm"
)

func (m *MedicalHistory) TableName() string {
	return "medical_history"
}

func (m *MedicalHistory) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeText, Constraints: orm.ConstraintPK},
		{Name: "patient_id", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "doctor_id", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "reservation_id", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "status", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "attention_at", Type: orm.TypeInt64, Constraints: orm.ConstraintNotNull},
		{Name: "reason", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "diagnostic", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "prescription", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "cie10_code", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "started_at", Type: orm.TypeInt64, Constraints: orm.ConstraintNone},
		{Name: "finished_at", Type: orm.TypeInt64, Constraints: orm.ConstraintNone},
		{Name: "patient_name_snapshot", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "patient_rut_snapshot", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "doctor_name_snapshot", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "doctor_specialty_snapshot", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "updated_at", Type: orm.TypeInt64, Constraints: orm.ConstraintNotNull},
	}
}

func (m *MedicalHistory) Values() []any {
	return []any{
		m.ID,
		m.PatientID,
		m.DoctorID,
		m.ReservationID,
		m.Status,
		m.AttentionAt,
		m.Reason,
		m.Diagnostic,
		m.Prescription,
		m.Cie10Code,
		m.StartedAt,
		m.FinishedAt,
		m.PatientNameSnapshot,
		m.PatientRutSnapshot,
		m.DoctorNameSnapshot,
		m.DoctorSpecialtySnapshot,
		m.UpdatedAt,
	}
}

func (m *MedicalHistory) Pointers() []any {
	return []any{
		&m.ID,
		&m.PatientID,
		&m.DoctorID,
		&m.ReservationID,
		&m.Status,
		&m.AttentionAt,
		&m.Reason,
		&m.Diagnostic,
		&m.Prescription,
		&m.Cie10Code,
		&m.StartedAt,
		&m.FinishedAt,
		&m.PatientNameSnapshot,
		&m.PatientRutSnapshot,
		&m.DoctorNameSnapshot,
		&m.DoctorSpecialtySnapshot,
		&m.UpdatedAt,
	}
}

var MedicalHistory_ = struct {
	TableName string
	ID string
	PatientID string
	DoctorID string
	ReservationID string
	Status string
	AttentionAt string
	Reason string
	Diagnostic string
	Prescription string
	Cie10Code string
	StartedAt string
	FinishedAt string
	PatientNameSnapshot string
	PatientRutSnapshot string
	DoctorNameSnapshot string
	DoctorSpecialtySnapshot string
	UpdatedAt string
}{
	TableName: "medical_history",
	ID: "id",
	PatientID: "patient_id",
	DoctorID: "doctor_id",
	ReservationID: "reservation_id",
	Status: "status",
	AttentionAt: "attention_at",
	Reason: "reason",
	Diagnostic: "diagnostic",
	Prescription: "prescription",
	Cie10Code: "cie10_code",
	StartedAt: "started_at",
	FinishedAt: "finished_at",
	PatientNameSnapshot: "patient_name_snapshot",
	PatientRutSnapshot: "patient_rut_snapshot",
	DoctorNameSnapshot: "doctor_name_snapshot",
	DoctorSpecialtySnapshot: "doctor_specialty_snapshot",
	UpdatedAt: "updated_at",
}

func ReadOneMedicalHistory(qb *orm.QB, model *MedicalHistory) (*MedicalHistory, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMedicalHistory(qb *orm.QB) ([]*MedicalHistory, error) {
	var results []*MedicalHistory
	err := qb.ReadAll(
		func() orm.Model { return &MedicalHistory{} },
		func(m orm.Model) { results = append(results, m.(*MedicalHistory)) },
	)
	return results, err
}

func (m *MeasurementType) TableName() string {
	return "measurement_type"
}

func (m *MeasurementType) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeText, Constraints: orm.ConstraintPK},
		{Name: "name", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "default_unit", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "min_normal", Type: orm.TypeFloat64, Constraints: orm.ConstraintNone},
		{Name: "max_normal", Type: orm.TypeFloat64, Constraints: orm.ConstraintNone},
		{Name: "is_active", Type: orm.TypeBool, Constraints: orm.ConstraintNotNull},
		{Name: "loinc_code", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "ucum_unit", Type: orm.TypeText, Constraints: orm.ConstraintNone},
	}
}

func (m *MeasurementType) Values() []any {
	return []any{
		m.ID,
		m.Name,
		m.DefaultUnit,
		m.MinNormal,
		m.MaxNormal,
		m.IsActive,
		m.LoincCode,
		m.UcumUnit,
	}
}

func (m *MeasurementType) Pointers() []any {
	return []any{
		&m.ID,
		&m.Name,
		&m.DefaultUnit,
		&m.MinNormal,
		&m.MaxNormal,
		&m.IsActive,
		&m.LoincCode,
		&m.UcumUnit,
	}
}

var MeasurementType_ = struct {
	TableName string
	ID string
	Name string
	DefaultUnit string
	MinNormal string
	MaxNormal string
	IsActive string
	LoincCode string
	UcumUnit string
}{
	TableName: "measurement_type",
	ID: "id",
	Name: "name",
	DefaultUnit: "default_unit",
	MinNormal: "min_normal",
	MaxNormal: "max_normal",
	IsActive: "is_active",
	LoincCode: "loinc_code",
	UcumUnit: "ucum_unit",
}

func ReadOneMeasurementType(qb *orm.QB, model *MeasurementType) (*MeasurementType, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMeasurementType(qb *orm.QB) ([]*MeasurementType, error) {
	var results []*MeasurementType
	err := qb.ReadAll(
		func() orm.Model { return &MeasurementType{} },
		func(m orm.Model) { results = append(results, m.(*MeasurementType)) },
	)
	return results, err
}

func (m *ClinicalMeasurement) TableName() string {
	return "clinical_measurement"
}

func (m *ClinicalMeasurement) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeText, Constraints: orm.ConstraintPK},
		{Name: "medical_history_id", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "measured_by_staff_id", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "measurement_type_id", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "value", Type: orm.TypeFloat64, Constraints: orm.ConstraintNotNull},
		{Name: "unit", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "measured_at", Type: orm.TypeInt64, Constraints: orm.ConstraintNotNull},
		{Name: "notes", Type: orm.TypeText, Constraints: orm.ConstraintNone},
	}
}

func (m *ClinicalMeasurement) Values() []any {
	return []any{
		m.ID,
		m.MedicalHistoryID,
		m.MeasuredByStaffID,
		m.MeasurementTypeID,
		m.Value,
		m.Unit,
		m.MeasuredAt,
		m.Notes,
	}
}

func (m *ClinicalMeasurement) Pointers() []any {
	return []any{
		&m.ID,
		&m.MedicalHistoryID,
		&m.MeasuredByStaffID,
		&m.MeasurementTypeID,
		&m.Value,
		&m.Unit,
		&m.MeasuredAt,
		&m.Notes,
	}
}

var ClinicalMeasurement_ = struct {
	TableName string
	ID string
	MedicalHistoryID string
	MeasuredByStaffID string
	MeasurementTypeID string
	Value string
	Unit string
	MeasuredAt string
	Notes string
}{
	TableName: "clinical_measurement",
	ID: "id",
	MedicalHistoryID: "medical_history_id",
	MeasuredByStaffID: "measured_by_staff_id",
	MeasurementTypeID: "measurement_type_id",
	Value: "value",
	Unit: "unit",
	MeasuredAt: "measured_at",
	Notes: "notes",
}

func ReadOneClinicalMeasurement(qb *orm.QB, model *ClinicalMeasurement) (*ClinicalMeasurement, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllClinicalMeasurement(qb *orm.QB) ([]*ClinicalMeasurement, error) {
	var results []*ClinicalMeasurement
	err := qb.ReadAll(
		func() orm.Model { return &ClinicalMeasurement{} },
		func(m orm.Model) { results = append(results, m.(*ClinicalMeasurement)) },
	)
	return results, err
}

func (m *HistoryDetail) TableName() string {
	return "history_detail"
}

func (m *HistoryDetail) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeText, Constraints: orm.ConstraintPK},
		{Name: "medical_history_id", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "catalog_item_id", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "quantity", Type: orm.TypeInt64, Constraints: orm.ConstraintNotNull},
		{Name: "item_name_snapshot", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "item_code_snapshot", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "item_price_snapshot", Type: orm.TypeFloat64, Constraints: orm.ConstraintNotNull},
	}
}

func (m *HistoryDetail) Values() []any {
	return []any{
		m.ID,
		m.MedicalHistoryID,
		m.CatalogItemID,
		m.Quantity,
		m.ItemNameSnapshot,
		m.ItemCodeSnapshot,
		m.ItemPriceSnapshot,
	}
}

func (m *HistoryDetail) Pointers() []any {
	return []any{
		&m.ID,
		&m.MedicalHistoryID,
		&m.CatalogItemID,
		&m.Quantity,
		&m.ItemNameSnapshot,
		&m.ItemCodeSnapshot,
		&m.ItemPriceSnapshot,
	}
}

var HistoryDetail_ = struct {
	TableName string
	ID string
	MedicalHistoryID string
	CatalogItemID string
	Quantity string
	ItemNameSnapshot string
	ItemCodeSnapshot string
	ItemPriceSnapshot string
}{
	TableName: "history_detail",
	ID: "id",
	MedicalHistoryID: "medical_history_id",
	CatalogItemID: "catalog_item_id",
	Quantity: "quantity",
	ItemNameSnapshot: "item_name_snapshot",
	ItemCodeSnapshot: "item_code_snapshot",
	ItemPriceSnapshot: "item_price_snapshot",
}

func ReadOneHistoryDetail(qb *orm.QB, model *HistoryDetail) (*HistoryDetail, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllHistoryDetail(qb *orm.QB) ([]*HistoryDetail, error) {
	var results []*HistoryDetail
	err := qb.ReadAll(
		func() orm.Model { return &HistoryDetail{} },
		func(m orm.Model) { results = append(results, m.(*HistoryDetail)) },
	)
	return results, err
}
